[package]
name = "solfege"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.119"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
strip = true
