[package]
name = "solfege"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "*"
serde = { version = "1.0.159", features = ["derive"] }
toml = "0.8.8"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
panic = "abort"
strip = true
