name: Check
on: push
jobs:
    Format:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v3
            - run: "cargo +nightly fmt --check"
    Build:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v3
            - run: "cargo build"
            - run: "cargo build --release"
    Test:
        runs-on: [self-hosted, linux]
        needs: Build
        steps:
            - uses: actions/checkout@v3
            - run: "cargo test"
